### ISSUE TITLE
strapi v5 support ?

### ISSUE THREAD

**Issue by medevod** [jakeFeldman/strapi-provider-upload-azure-storage#100]
Is the tool compatible with strapi 5?

Instance through docker doesn't start , i'm encountering an error when instantiating BlobServiceClient

For the moment, I don't know whether it's an incompatibility du to the provider or a configuration problem specific to strapi V5.

In v4, everything's fine with same configuration

here's container output :

2024-12-06 22:12:54 yarn run v1.22.19
2024-12-06 22:12:54 $ strapi start
2024-12-06 22:12:56 [2024-12-06 21:12:56.655] error: [object Object]
2024-12-06 22:12:56 Error: [object Object]
2024-12-06 22:12:56     at makeBlobServiceClient (/srv/app/node_modules/strapi-provider-upload-azure-storage/dist/index.js:48:19)
2024-12-06 22:12:56     at Object.init (/srv/app/node_modules/strapi-provider-upload-azure-storage/dist/index.js:130:31)
2024-12-06 22:12:56     at createProvider (/srv/app/node_modules/@strapi/upload/dist/_chunks/index-D57iKFts.js:363:38)
2024-12-06 22:12:56     at Object.register (/srv/app/node_modules/@strapi/upload/dist/_chunks/index-D57iKFts.js:327:39)
2024-12-06 22:12:56     at Object.register (/srv/app/node_modules/@strapi/core/dist/domain/module/index.js:45:46)
2024-12-06 22:12:56     at Object.register (/srv/app/node_modules/@strapi/core/dist/registries/modules.js:28:19)
2024-12-06 22:12:56     at async Strapi.runPluginsLifecycles (/srv/app/node_modules/@strapi/core/dist/Strapi.js:410:5)
2024-12-06 22:12:56     at async Strapi.register (/srv/app/node_modules/@strapi/core/dist/Strapi.js:327:5)
2024-12-06 22:12:56     at async Strapi.load (/srv/app/node_modules/@strapi/core/dist/Strapi.js:317:5)
2024-12-06 22:12:56     at async Strapi.start (/srv/app/node_modules/@strapi/core/dist/Strapi.js:208:9)
2024-12-06 22:12:56 [2024-12-06 21:12:56.657] info: Shutting down Strapi
2024-12-06 22:12:56 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-12-06 22:12:56 error Command failed with exit code 1.

**Comment by medevod** [comment]
Related to PR  #85 

I solved this issue by adding missing but required authType option in plugins.js file 
section:  $.upload.config.providerOptions

**Comment by jakeFeldman** [comment]
Thanks! Glad that fixed it for you. I have not tested with strapi v5 but good to know it is working

**Comment by nknaviro** [comment]
The issue still persist ..
