### ISSUE TITLE
Deleting media 404 error

### ISSUE THREAD

**Issue by colin-precisionos** [jakeFeldman/strapi-provider-upload-azure-storage#80]
When I delete media from the admin panel media library, I receive a 404 message.  
This what the output looks like:
[2023-10-10 11:58:15.316] error: The specified blob does not exist.
RequestId:32a84387-a01e-0012-79ab-fbe3ce000000
Time:2023-10-10T18:58:15.3378526Z
RestError: The specified blob does not exist.
RequestId:32a84387-a01e-0012-79ab-fbe3ce000000
Time:2023-10-10T18:58:15.3378526Z
    at handleErrorResponse (...\node_modules\@azure\core-http\dist\index.js:3146:19)
    at ...\node_modules\@azure\core-http\dist\index.js:3082:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async StorageRetryPolicy.attemptSendRequest (...\node_modules\@azure\storage-blob\dist\index.js:14396:24)
    at async StorageClientContext.sendOperationRequest (...\node_modules\@azure\core-http\dist\index.js:4865:31)
    at async BlobClient.delete (...\node_modules\@azure\storage-blob\dist\index.js:19568:20)

The URL for the media exists, and I can access it.  The media file was uploaded via the API uploader with a folder path specified.  It looks like your code assumes the default path?

**Comment by jakeFeldman** [comment]
Thanks for reporting. I can take a look at this later this week

**Comment by Waffe** [comment]
This is still an issue, is there any update?

`2024-06-10T19:28:43.4126059Z [2024-06-10 19:28:43.412] [32mhttp[39m: DELETE /upload/files/8 (2 ms) 401
2024-06-10T19:28:52.4010123Z [2024-06-10 19:28:52.400] [31merror[39m: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
2024-06-10T19:28:52.4012077Z RequestId:b39ca715-c01e-0006-1d6c-bb40b9000000
2024-06-10T19:28:52.4012398Z Time:2024-06-10T19:28:52.3998965Z</Message></Error>
2024-06-10T19:28:52.4012670Z Error: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
2024-06-10T19:28:52.4012937Z RequestId:b39ca715-c01e-0006-1d6c-bb40b9000000
2024-06-10T19:28:52.4013168Z Time:2024-06-10T19:28:52.3998965Z</Message></Error>
2024-06-10T19:28:52.4013398Z     at new RestError (/home/site/wwwroot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:2479:28)
2024-06-10T19:28:52.4013643Z     at /home/site/wwwroot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3644:37
2024-06-10T19:28:52.4013880Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-10T19:28:52.4014103Z     at async Object.remove (/home/site/wwwroot/node_modules/@strapi/plugin-upload/server/services/upload.js:431:7)
2024-06-10T19:28:52.4014341Z     at async Object.destroy (/home/site/wwwroot/node_modules/@strapi/plugin-upload/server/controllers/content-api.js:71:5)
2024-06-10T19:28:52.4014588Z     at async returnBodyMiddleware (/home/site/wwwroot/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
2024-06-10T19:28:52.4014829Z     at async policiesMiddleware (/home/site/wwwroot/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
2024-06-10T19:28:52.4015063Z     at async /home/site/wwwroot/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
2024-06-10T19:28:52.4015281Z     at async /home/site/wwwroot/node_modules/@strapi/strapi/dist/middlewares/powered-by.js:9:5
2024-06-10T19:28:52.4015515Z     at async /home/site/wwwroot/node_modules/@strapi/strapi/dist/middlewares/errors.js:8:7
2024-06-10T19:28:52.4015744Z     at async /home/site/wwwroot/node_modules/@strapi/strapi/dist/middlewares/body.js:45:9
2024-06-10T19:28:52.4016034Z     at async cors (/home/site/wwwroot/node_modules/@koa/cors/index.js:106:16)
2024-06-10T19:28:52.4016282Z     at async /home/site/wwwroot/node_modules/@strapi/strapi/dist/middlewares/logger.js:6:5
2024-06-10T19:28:52.4016516Z     at async session (/home/site/wwwroot/node_modules/koa-session/index.js:41:7)
2024-06-10T19:28:52.4016748Z     at async middleware (/home/site/wwwroot/node_modules/@strapi/strapi/dist/services/metrics/middleware.js:20:5)
2024-06-10T19:28:52.4024025Z [2024-06-10 19:28:52.402] [32mhttp[39m: DELETE /api/upload/files/8 (78 ms) 404`
