### ISSUE TITLE
[bug] start Strapi server with an unexpected error thrown

### ISSUE THREAD

**Issue by TechQuery** [jakeFeldman/strapi-provider-upload-azure-storage#88]
## Summary

@jakeFeldman After I upgrade my existed project to `strapi@4.20.2` & `strapi-provider-upload-azure-storage@3.4.0`, I can't start the Development & Production servers, but the Building works well.

## Error log

```text
$ pnpm develop

> @ohp/web-server@0.14.0 develop ~/Desktop/OpenHackathon-server
> strapi develop

✔ Cleaning dist dir (51ms)
⠋ Building build context
⠙ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (770ms)
✔ Creating admin (59502ms)
⠇ Loading Strapi
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                     │
│   Error: [object Object]                                                                                                            │
│   at makeBlobServiceClient (~/Desktop/OpenHackathon-server/node_modules/strapi-provider-upload-azure-storage/dist/index.js:48:19)   │
│   at Object.init (~/Desktop/OpenHackathon-server/node_modules/strapi-provider-upload-azure-storage/dist/index.js:130:31)            │
│   at createProvider (~/Desktop/OpenHackathon-server/node_modules/@strapi/plugin-upload/server/register.js:60:37)                    │
│   at module.exports [as register] (~/Desktop/OpenHackathon-server/node_modules/@strapi/plugin-upload/server/register.js:16:38)      │
│   at Object.register (~/Desktop/OpenHackathon-server/node_modules/@strapi/strapi/dist/core/domain/module/index.js:46:46)            │
│   at Object.register (~/Desktop/OpenHackathon-server/node_modules/@strapi/strapi/dist/core/registries/modules.js:28:19)             │
│   at async Strapi.runLifecyclesFunctions (~/Desktop/OpenHackathon-server/node_modules/@strapi/strapi/dist/Strapi.js:440:5)          │
│   at async Strapi.register (~/Desktop/OpenHackathon-server/node_modules/@strapi/strapi/dist/Strapi.js:361:5)                        │
│   at async Strapi.load (~/Desktop/OpenHackathon-server/node_modules/@strapi/strapi/dist/Strapi.js:425:5)                            │
│   at async Object.develop (~/Desktop/OpenHackathon-server/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:837:28)         │
│                                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

## Reproduce code

kaiyuanshe/OpenHackathon-server#11

**Comment by jakeFeldman** [comment]
Hey @TechQuery if you downgrade the plugin to 3.3.0 does the dev server run?

**Comment by jakeFeldman** [comment]
Thanks for confirming. 

I made a mistake when upgrading the version to v3.4.0. I should have made it a major version.

Did you update your config to include the new `authType` property?

https://github.com/jakeFeldman/strapi-provider-upload-azure-storage?tab=readme-ov-file#usage

**Comment by TechQuery** [comment]
> Thanks for confirming.
> 
> I made a mistake when upgrading the version to v3.4.0. I should have made it a major version.
> 
> Did you update your config to include the new `authType` property?
> 
> https://github.com/jakeFeldman/strapi-provider-upload-azure-storage?tab=readme-ov-file#usage

No, I didn't check the ReadMe as this is a minor version.

And it works after I add `authType: "default"` into the configuration.

**Comment by TechQuery** [comment]
> Thanks for confirming.
> 
> I made a mistake when upgrading the version to v3.4.0. I should have made it a major version.
> 
> Did you update your config to include the new `authType` property?
> 
> https://github.com/jakeFeldman/strapi-provider-upload-azure-storage?tab=readme-ov-file#usage

No, I didn't check the ReadMe as this is a minor version.

And it works after I add `authType: "default"` into the configuration.
